// worker.js - True Morphological Opening Engine

self.onmessage = function(e) {
    const { imageData, minStrokePixels, targetWidth, targetHeight, sizeValid } = e.data;
    const data = imageData.data;
    const w = targetWidth;
    const h = targetHeight;
    
    let hasGrayscale = false;
    let hasThinStrokes = false;
    
    const overlayData = new Uint8ClampedArray(data.length);
    const grid = new Float8Array(w * h); // 1 = ink, 0 = background
    
    // STEP 1: Basic Binary Thresholding (Ignore AA edges for now)
    for (let i = 0; i < data.length; i += 4) {
        const a = data[i+3];
        if (a < 128) continue; // Skip mostly transparent
        
        const brightness = (data[i] + data[i+1] + data[i+2]) / 3;
        if (brightness < 200) { 
            grid[(i / 4)] = 1; 
        }
    }
    
    // Safety Padding: Ensure border pixels are treated as edges so DT calculates correctly
    for(let x=0; x<w; x++) { grid[x] = 0; grid[(h-1)*w + x] = 0; }
    for(let y=0; y<h; y++) { grid[y*w] = 0; grid[y*w + w - 1] = 0; }
    
    self.postMessage({ type: 'progress', percent: 15 });

    // STEP 2: Pass 1 Distance Transform (Erosion - Find distance to Background)
    const DT1 = new Float32Array(w * h);
    for (let i = 0; i < grid.length; i++) {
        DT1[i] = grid[i] === 1 ? Infinity : 0;
    }
    
    // 8-way Chebyshev distance (Square Radius)
    // Forward Pass
    for (let y = 1; y < h - 1; y++) {
        for (let x = 1; x < w - 1; x++) {
            let i = y * w + x;
            if (grid[i] === 1) {
                DT1[i] = Math.min(DT1[i], DT1[i-1]+1, DT1[i-w-1]+1, DT1[i-w]+1, DT1[i-w+1]+1);
            }
        }
    }
    // Backward Pass
    for (let y = h - 2; y >= 0; y--) {
        for (let x = w - 2; x >= 0; x--) {
            let i = y * w + x;
            if (grid[i] === 1) {
                DT1[i] = Math.min(DT1[i], DT1[i+1]+1, DT1[i+w+1]+1, DT1[i+w]+1, DT1[i+w-1]+1);
            }
        }
    }
    self.postMessage({ type: 'progress', percent: 40 });

    // STEP 3: Smart Grayscale Check (Bypass Anti-Aliasing)
    // We ONLY check for grayscale on "Core" pixels (pixels at least 3 levels deep).
    // This perfectly ignores the gray edges generated by pdf.js vector rendering.
    for (let i = 0; i < grid.length; i++) {
        if (grid[i] === 1 && DT1[i] > 2) {
            const idx = i * 4;
            const brightness = (data[idx] + data[idx+1] + data[idx+2]) / 3;
            // Strict test inside the shape
            if (brightness > 20 && brightness < 235) {
                hasGrayscale = true;
                break; // One true gray pixel deep inside is enough to fail
            }
        }
    }
    self.postMessage({ type: 'progress', percent: 50 });

    // STEP 4: Define True Cores
    const radiusThreshold = minStrokePixels / 2;
    const DT2 = new Float32Array(w * h);
    
    // A core is any pixel whose distance to the background is >= our required radius
    for (let i = 0; i < DT1.length; i++) {
        DT2[i] = (DT1[i] >= radiusThreshold) ? 0 : Infinity;
    }

    // STEP 5: Pass 2 Distance Transform (Dilation - Measure outward from Cores)
    // Forward Pass
    for (let y = 1; y < h - 1; y++) {
        for (let x = 1; x < w - 1; x++) {
            let i = y * w + x;
            if (DT2[i] !== 0) {
                DT2[i] = Math.min(DT2[i], DT2[i-1]+1, DT2[i-w-1]+1, DT2[i-w]+1, DT2[i-w+1]+1);
            }
        }
    }
    // Backward Pass & Flagging
    for (let y = h - 2; y >= 0; y--) {
        for (let x = w - 2; x >= 0; x--) {
            let i = y * w + x;
            if (DT2[i] !== 0) {
                DT2[i] = Math.min(DT2[i], DT2[i+1]+1, DT2[i+w+1]+1, DT2[i+w]+1, DT2[i+w-1]+1);
            }

            // THE FINAL STROKE CHECK:
            // If it's an ink pixel, but its distance to the nearest Core is larger than the allowed radius...
            // It means it belongs to a shape too thin to have generated a Core.
            if (grid[i] === 1 && DT2[i] >= radiusThreshold) {
                hasThinStrokes = true;
                // Paint Neon Pink
                overlayData[i*4] = 255; overlayData[i*4+1] = 16; overlayData[i*4+2] = 122; overlayData[i*4+3] = 255;
            }
        }
    }
    self.postMessage({ type: 'progress', percent: 95 });

    self.postMessage({
        type: 'complete',
        results: {
            hasGrayscale, hasThinStrokes, sizeValid, overlayBuffer: overlayData.buffer, width: w, height: h
        }
    }, [overlayData.buffer]); 
};
